version: '3.8'

services:
  # Your existing Snake game app
  snake-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - snake-network

  # Automatic streaming service
  pump-streamer:
    build: 
      context: .
      dockerfile: Dockerfile.streamer
    depends_on:
      - snake-app
    environment:
      - RTMP_URL=${RTMP_URL}
      - SNAKE_GAME_URL=http://snake-app:5000
      - DISPLAY=:1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    privileged: true
    restart: unless-stopped
    networks:
      - snake-network

networks:
  snake-network:
    driver: bridge